global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'ml-api'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:8000']

    # Scrape interval for this job
    scrape_interval: 10s

    # Metrics path
    metrics_path: '/metrics'

    # Relabeling rules
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*)'
        replacement: '${1}'

  # Optional: Add other services if needed
  # - job_name: 'other-service'
  #   static_configs:
  #     - targets: ['localhost:8080']

# Alerting rules (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

# Recording rules (optional)
# rule_files:
#   - "recording_rules.yml"
